name: requirements_mac

channels:
  - defaults
  - conda-forge
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - expat=2.6.4
  - libffi=3.4.4
  - openssl=3.0.15
  - python=3.12.7
  - setuptools=75.8.0
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - aiohappyeyeballs==2.4.6
      - aiohttp==3.10.11
      - aiosignal==1.3.2
      - altair==5.5.0
      - annotated-types==0.7.0
      - anyio==4.8.0
      - attrs==25.1.0
      - beautifulsoup4==4.13.3
      - blinker==1.9.0
      - cachetools==5.5.2
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - click==8.1.8
      - colorama==0.4.6
      - dataclasses-json==0.5.14
      - distro==1.9.0
      - dnspython==2.7.0
      - faiss-cpu==1.10.0
      - filelock==3.17.0
      - frozendict==2.4.6
      - frozenlist==1.5.0
      - fsspec==2025.2.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - greenlet==3.1.1
      - h11==0.14.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - huggingface-hub==0.29.1
      - idna==3.10
      - iniconfig==2.0.0
      - jinja2==3.1.5
      - jiter==0.8.2
      - joblib==1.4.2
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - langchain>=0.1.0
      - langchain-community>=0.0.20
      - langchain-core>=0.3.40
      - langchain-pinecone>=0.2.3
      - langchain-tests>=0.3.12
      - langsmith>=0.3.11
      - loguru==0.7.3
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - marshmallow==3.26.1
      - mdurl==0.1.2
      - mpmath==1.3.0
      - multidict==6.1.0
      - multitasking==0.0.11
      - mypy-extensions==1.0.0
      - narwhals==1.28.0
      - networkx==3.4.2
      - newsapi-python==0.2.7
      - nltk==3.9.1
      - numexpr==2.10.2
      - numpy==1.26.4
      - openai==1.64.0
      - openapi-schema-pydantic==1.2.4
      - orjson==3.10.15
      - packaging==23.2
      - pandas==2.2.3
      - peewee==3.17.9
      - pillow==11.1.0
      - pinecone==5.4.2
      - pinecone-client==2.2.4
      - pinecone-plugin-inference==3.1.0
      - pinecone-plugin-interface==0.0.7
      - pip==25.0.1
      - platformdirs==4.3.6
      - pluggy==1.5.0
      - propcache==0.3.0
      - protobuf==3.20.3
      - py-lets-be-rational==1.0.1
      - py-vollib==1.0.1
      - pyarrow==19.0.1
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydeck==0.9.1
      - pygments==2.19.1
      - pypdf==3.15.1
      - pytest==8.3.4
      - pytest-asyncio==0.25.3
      - pytest-socket==0.7.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.0
      - pytz==2025.1
      - pyyaml==6.0.2
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.3
      - requests-toolbelt==1.0.0
      - rich==13.9.4
      - rpds-py==0.23.1
      - safetensors==0.5.3
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - sentence-transformers==3.4.1
      - sentencepiece==0.2.0
      - simplejson==3.20.1
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.6
      - sqlalchemy==2.0.38
      - streamlit==1.42.2
      - sympy==1.13.1
      - syrupy==4.8.2
      - tabulate==0.9.0
      - tenacity==8.5.0
      - threadpoolctl==3.5.0
      - tokenizers==0.21.0
      - toml==0.10.2
      - torch==2.6.0
      - torchvision==0.21.0
      - tornado==6.4.2
      - tqdm==4.67.1
      - transformers==4.49.0
      - typing-extensions==4.12.2
      - typing-inspect==0.9.0
      - tzdata==2025.1
      - urllib3==2.3.0
      - watchdog==6.0.0
      - yarl==1.18.3
      - yfinance==0.2.54
      - zstandard==0.23.0