name: options_sk
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - altair=5.0.1
  - arrow-cpp=19.0.0
  - attrs=24.3.0
  - aws-c-auth=0.6.19
  - aws-c-cal=0.5.20
  - aws-c-common=0.8.5
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.15
  - aws-c-http=0.6.25
  - aws-c-io=0.13.10
  - aws-c-mqtt=0.7.13
  - aws-c-s3=0.1.51
  - aws-c-sdkutils=0.1.6
  - aws-checksums=0.1.13
  - aws-crt-cpp=0.18.16
  - aws-sdk-cpp=1.11.212
  - blas=1.0
  - blinker=1.9.0
  - boost-cpp=1.82.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.12.31
  - cachetools=5.5.1
  - certifi=2025.1.31
  - charset-normalizer=3.3.2
  - click=8.1.7
  - contourpy=1.2.1
  - cycler=0.11.0
  - fonttools=4.55.3
  - freetype=2.12.1
  - gflags=2.2.2
  - gitdb=4.0.7
  - gitpython=3.1.43
  - glog=0.5.0
  - icu=73.1
  - idna=3.7
  - importlib_resources=6.4.0
  - jinja2=3.1.5
  - jpeg=9e
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.7.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20240116.2
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=8.12.1
  - libcxx=14.0.6
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libgrpc=1.62.2
  - libiconv=1.16
  - libnghttp2=1.57.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libprotobuf=4.25.3
  - libssh2=1.11.1
  - libthrift=0.15.0
  - libtiff=4.5.1
  - libwebp-base=1.3.2
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markdown-it-py=2.2.0
  - markupsafe=3.0.2
  - matplotlib=3.9.2
  - matplotlib-base=3.9.2
  - mdurl=0.1.0
  - ncurses=6.4
  - numexpr=2.10.1
  - numpy=2.0.2
  - numpy-base=2.0.2
  - openjpeg=2.5.2
  - openssl=3.0.15
  - orc=2.0.1
  - packaging=24.2
  - pandas=2.2.3
  - pillow=11.1.0
  - pip=25.0
  - protobuf=4.25.3
  - pyarrow=19.0.0
  - pydeck=0.9.1
  - pygments=2.15.1
  - pyparsing=3.2.0
  - pysocks=1.7.1
  - python=3.9.20
  - python-dateutil=2.9.0post0
  - python-tzdata=2023.3
  - pytz=2024.1
  - re2=2022.04.01
  - readline=8.2
  - referencing=0.30.2
  - requests=2.32.3
  - rich=13.9.4
  - rpds-py=0.22.3
  - seaborn=0.13.2
  - setuptools=72.1.0
  - six=1.16.0
  - smmap=4.0.0
  - snappy=1.2.1
  - sqlite=3.45.3
  - streamlit=1.41.1
  - tenacity=9.0.0
  - tk=8.6.14
  - toml=0.10.2
  - toolz=1.0.0
  - tornado=6.4.2
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2025a
  - unicodedata2=15.1.0
  - urllib3=2.3.0
  - utf8proc=2.6.1
  - wheel=0.45.1
  - xz=5.6.4
  - zipp=3.21.0
  - zlib=1.2.13
  - zstd=1.5.6